apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Base de datos y Usuario (se leen en el Deployment de PostgreSQL)
  POSTGRES_DB: bGFiM3Y=                 # lab3v
  POSTGRES_USER: cG9zdGdyZXM=           # postgres
  POSTGRES_PASSWORD: cHN2YWxlMDcxOTQ3   # psvale071947